### ISSUE TITLE
Na funcionalidade "Listar Projetos de Pesquisa em Andamento" existem projetos em falta

### ISSUE THREAD

**Issue by JoseCarlosRN** [pcqhfilho/sysicomp#23]
De acordo com o icomp números antigo, faltam projetos de pesquisa em andamento na funcionalidade "Listar Projetos de Pesquisa em Andamento".

Sistema iComp em Números antigo:
<a href="http://i.imgur.com/w4vuM5T.png">
  <img src="http://imgur.com/w4vuM5Tl.png" />
</a>

Sistem iComp em Números em desenvolvimento:
<a href="http://i.imgur.com/VqTsGuR.png">
  <img src="http://imgur.com/VqTsGuRl.png" />
</a>

Percebe-se que está faltando os projetos dos anos de 2016 ao 2017.

**Comment by MHiroshiSaito** [comment]
Não existe este bug pois bug não foi especificado.

**Comment by JoseCarlosRN** [comment]
Descrição mais detalhada adicionada.

**Comment by pavloceza** [comment]
a falta dos projetos anteriormente era consequencia do banco nao estar atualizado de acordo com os curriculos lattes dos docentes
