### ISSUE TITLE
A pesquisa por alunos egressos não está filtrando por data.

### ISSUE THREAD

**Issue by thiegobarros** [pcqhfilho/sysicomp#31]
Ao inserir um ano no campo de pesquisa de data, o filtro não retorna ano referente ao inserido. (Não acontece nada)
![issue31](https://user-images.githubusercontent.com/18040615/33103961-dfc5ed86-cefb-11e7-9a29-3341cff6bcae.png)

**Comment by JoseCarlosRN** [comment]
Issue Resolvida.
