### ISSUE TITLE
Menu superior, no modo de tela reduzida, não está fechando após abrir.

### ISSUE THREAD

**Issue by thiegobarros** [pcqhfilho/sysicomp#36]
Menu superior de acesso rápido aos modulos do sistema, ele surge quando reduzimos a tela(responsividade). Quando abrimos, ele não fecha e prejudica a visão da tela, segue o print em anexo.

![print_menuaberto](https://user-images.githubusercontent.com/18040615/33431807-1bcc0f16-d5ac-11e7-9bf5-cb68b4d31300.png)
![print_menufechado](https://user-images.githubusercontent.com/18040615/33431808-1c258906-d5ac-11e7-9ac6-83e84eb65c28.png)

**Comment by pavloceza** [comment]
problema no javascript resolvido
