### ISSUE TITLE
Em projetos, o painel de projeto não está fechando após abrir.

### ISSUE THREAD

**Issue by thiegobarros** [pcqhfilho/sysicomp#37]
Em projetos, o painel relacionado a um projeto em andamento, após abrirmos, quando clicamos pra fechar, ele não está fechando. Nota-se uma pequena travada evitando o ato de fechar.

![print_projaberto](https://user-images.githubusercontent.com/18040615/33432241-a12266a0-d5ad-11e7-829f-03705c5fe276.png)
![print_projfechado](https://user-images.githubusercontent.com/18040615/33432242-a14ef260-d5ad-11e7-8326-92afae138ae1.png)

**Comment by pavloceza** [comment]
problema no javascript resolvido
